(
{
  (
    basic: {
      [
        (
          dur: 1,
          amp: 0.065
        ),
        (
          dur: 2/3,
          amp: 0.095
        ),
        (
          dur: 1/3,
          amp: 0.050
        ),
        (
          dur: 1,
          amp: 0.065
        ),
        (
          dur: 2/3,
          amp: 0.105
        ),
        (
          dur: 1/3,
          amp: 0.050
        )
      ]
    }
  )
}.value
)
